export enum MutationTypes {
  SET_SUBSCRIPTION = "SET_SUBSCRIPTION",
  SET_SUBSCRIPTIONS = "SET_SUBSCRIPTIONS",
  SET_SUBSCRIPTION_ANALYS_DATA = "SET_SUBSCRIPTION_ANALYS_DATA",
  SET_SUBSCRIPTION_PAGINATION = "SET_SUBSCRIPTION_PAGINATION",
  UPDATE_SUBSCRIPTION_PAGINATION = "UPDATE_SUBSCRIPTION_PAGINATION",
}
