export enum ActionTypes {
  GET_COMMENTS = "GET_COMMENTS",
  GET_COMMENT = "GET_COMMENT",
  CREATE_COMMENT = "CREATE_COMMENT",
  UPDATE_COMMENT = "UPDATE_COMMENT",
  DELETE_COMMENT = "DELETE_COMMENT",
  UPLOAD_COMMENT_THUMBNAIL = "UPLOAD_COMMENT_THUMBNAIL",
  HARD_DELETE_COMMENT = "HARD_DELETE_COMMENT",
}
