export enum MutationTypes {
  SET_FEEDBACK = "SET_FEEDBACK",
  SET_FEEDBACKS = "SET_FEEDBACKS",
  SET_FEEDBACK_ANALYS_DATA = "SET_FEEDBACK_ANALYS_DATA",
  UPDATE_FEEDBACK_DATA = "UPDATE_FEEDBACK_DATA",
}
