export enum ActionTypes {
  GET_POSTS = "GET_POSTS",
  GET_POST = "GET_POST",
  CREATE_POST = "CREATE_POST",
  UPDATE_POST = "UPDATE_POST",
  DELETE_POST = "DELETE_POST",
  UPLOAD_POST_THUMBNAIL = "UPLOAD_POST_THUMBNAIL",
  HARD_DELETE_POST = "HARD_DELETE_POST",
}
