export enum ActionTypes {
  GET_USER = "GET_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
  UPLOAD_USER_AVATAR = "UPLOAD_USER_AVATAR",
  HARD_DELETE_USER = "HARD_DELETE_USER",
  UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD",
  VERIFY_EMAIL = "VERIFY_EMAIL",
}
