export enum ActionTypes {
  GET_POST = "GET_POST",
  GET_POSTS_PAGINATED = "GET_POSTS_PAGINATED",
  GET_SUGGESTION_POSTS = "GET_SUGGESTION_POSTS",
  UPDATE_POST = "UPDATE_POST",
  EXPORT_POST_PDF = "EXPORT_POST_PDF",
  GET_POST_BY_SLUG = "GET_POST_BY_SLUG",
}
