export enum ActionTypes {
  GET_POSTS_PAGINATED = "GET_POSTS_PAGINATED",
  GET_SUGGESTION_POSTS = "GET_SUGGESTION_POSTS",
  EXPORT_POST_PDF = "EXPORT_POST_PDF",
  GET_POST_BY_SLUG = "GET_POST_BY_SLUG",
  INCREASE_POST_VIEWS = "INCREASE_POST_VIEWS",
}
