export enum MutationTypes {
  SET_POST = "SET_POST",
  SET_POSTS = "SET_POSTS",
  SET_POST_PAGINATION = "SET_POST_PAGINATION",
  SET_LATEST_POSTS = "SET_LATEST_POSTS",
  SET_POST_SEARCH_QUERY = "SET_POST_SEARCH_QUERY",
  SET_LOADING = "SET_LOADING",
}
