export enum ActionTypes {
  GET_GALLERIES_BY_PARENT = "GET_GALLERIES_BY_PARENT",
  GET_GALLERIES_PAGINATED = "GET_GALLERIES_PAGINATED",
  DELETE_GALLERY_ITEM = "DELETE_GALLERY_ITEM",
  HARD_DELETE_GALLERY = "HARD_DELETE_GALLERY",
  CREATE_GALLERY = "CREATE_GALLERY",
  UPLOAD_GALLERY_ITEM = "UPLOAD_GALLERY_ITEM",
  GET_GALLERY = "GET_GALLERY",
}
