export enum MutationTypes {
  SET_ME = "SET_ME",
  SET_HAS_USER = "SET_HAS_USER",
  UPDATE_ME_DATA = "UPDATE_ME_DATA",
  SET_IS_OPEN_2FA_MODAL = "SET_IS_OPEN_2FA_MODAL",
  SET_IS_OPEN_2FA_QR_MODAL = "SET_IS_OPEN_2FA_QR_MODAL",
  SET_QR_DATA = "SET_QR_DATA",
  SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN",
}
