export enum ActionTypes {
  GET_CATEGORIES = "GET_CATEGORIES",
  GET_CATEGORY = "GET_CATEGORY",
  GET_CATEGORY_TITLES = "GET_CATEGORY_TITLES",
  GET_OUTSTANDING_CATEGORIES_PAGINATED = "GET_OUTSTANDING_CATEGORIES_PAGINATED",
  GET_CATEGORY_BY_SLUG = "GET_CATEGORY_BY_SLUG",
}
