export enum MutationTypes {
  SET_CATEGORY = "SET_CATEGORY",
  SET_CATEGORIES = "SET_CATEGORIES",
  SET_CATEGORY_TITLES = "SET_CATEGORY_TITLES",
  SET_CATEGORIES_PAGINATION = "SET_CATEGORIES_PAGINATION",
}
