version: "2.0"

services: 
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  
  redis-admin:
    image: erikdubbelboer/phpredisadmin
    restart: always
    ports:
      - 8085:80
    depends_on:
      - redis
    environment:
      REDIS_1_HOST: redis
      REDIS_1_NAME: redis
      REDIS_1_PORT: 6379
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo/data:/data/db
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    volumes:
      - ./mongo/data:/data/db
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_ADMIN_URL}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_ADMIN_SERVER}
