export enum ActionTypes {
  GET_COMMENTS = "GET_COMMENTS",
  GET_COMMENT = "GET_COMMENT",
  CREATE_COMMENT = "CREATE_COMMENT",
  UPDATE_COMMENT = "UPDATE_COMMENT",
  DELETE_COMMENT = "DELETE_COMMENT",
  HARD_DELETE_COMMENT = "HARD_DELETE_COMMENT",
  GET_COMMENTS_BY_POST_PAGINATED = "GET_COMMENTS_BY_POST_PAGINATED",
  REPLY_COMMENT = "REPLY_COMMENT",
  COUNT_COMMENT_BY_POST = "COUNT_COMMENT_BY_POST",
  GET_COMMENTS_BY_PARENT = "GET_COMMENTS_BY_PARENT",
}
