export enum ActionTypes {
  GET_USERS = "GET_USERS",
  GET_USER = "GET_USER",
  CREATE_USER = "CREATE_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
  UPLOAD_USER_AVATAR = "UPLOAD_USER_AVATAR",
  HARD_DELETE_USER = "HARD_DELETE_USER",
}
