export enum ActionTypes {
  CREATE_POST_BOOKMARK = "CREATE_POST_BOOKMARK",
  CREATE_OR_DELETE_POST_BOOKMARK = "CREATE_OR_DELETE_POST_BOOKMARK",
  REMOVE_POST_BOOKMARK = "REMOVE_POST_BOOKMARK",
  GET_POST_BOOKMARKS_PAGINATED = "GET_POST_BOOKMARKS_PAGINATED",
}
