export enum MutationTypes {
  SET_POST_BOOKMARK = "SET_POST_BOOKMARK",
  SET_POST_BOOKMARKS = "SET_POST_BOOKMARKS",
  SET_POST_BOOKMARK_PAGINATION = "SET_POST_BOOKMARK_PAGINATION",
  UPDATE_POST_BOOKMARK_DATA = "UPDATE_POST_BOOKMARK_DATA",
  SET_POST_BOOKMARKS_COUNT = "SET_POST_BOOKMARKS_COUNT",
  SET_LOADING = "SET_LOADING",
}
