export enum ActionTypes {
  GET_FEEDBACKS = "GET_FEEDBACKS",
  GET_FEEDBACK = "GET_FEEDBACK",
  CREATE_FEEDBACK = "CREATE_FEEDBACK",
  UPDATE_FEEDBACK = "UPDATE_FEEDBACK",
  DELETE_FEEDBACK = "DELETE_FEEDBACK",
}
