export enum ActionTypes {
  GET_PASSWORD_RESET_BY_CODE = "GET_PASSWORD_RESET_BY_CODE",
  CREATE_PASSWORD_RESET = "CREATE_PASSWORD_RESET",
  HARD_DELETE_PASSWORD_RESET = "HARD_DELETE_PASSWORD_RESET",
  RESET_PASSWORD = "RESET_PASSWORD",
}
