export enum ActionTypes {
  GET_PASSWORD_RESET_BY_EMAIL_AND_CODE = "GET_PASSWORD_RESET_BY_EMAIL_AND_CODE",
  CREATE_PASSWORD_RESET = "CREATE_PASSWORD_RESET",
  HARD_DELETE_PASSWORD_RESET = "HARD_DELETE_PASSWORD_RESET",
}
