# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
       run:
         working-directory: ./core/server

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.4.x
        cache: yarn
        cache-dependency-path: './core/server/yarn.lock'
    
    - name: Cache node-modules
      id: cache-yarn
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-key: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - if: ${{ steps.cache-yarn.outputs.cache-hit != 'true' }}
      name: 'List the state of node modules'
      continue-on-error: true
      run: yarn list

    - name: Install dependencies
      run: yarn install --pure-lockfile --silent

    - name: Build TypeScript
      run: yarn ts:build

    - name: Unit testing
      env:
        DIFF_FILE: get_diff_files.txt
        CHANGELOG_CACHE_FILE_PATH: __tests__/__fixtures__/changelog-feed.json
      run: yarn test:ci
